import { useState } from 'react';
import type { FormEvent } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import api from '../lib/api';
import { AuthShell } from '../components/AuthShell';

export default function ResetPassword() {
  const navigate = useNavigate(); const [searchParams] = useSearchParams();
  const [email, setEmail] = useState(searchParams.get('email') || ''); const resetToken = searchParams.get('token') || '';
  const [newPassword, setNewPassword] = useState(''); const [showPassword, setShowPassword] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function handleSubmit(event: FormEvent) { event.preventDefault(); setMessage(''); setError(''); setLoading(true); try { const response = await api.post('/auth/reset-password', { email, resetToken, newPassword }); setMessage(response.data.message || 'Password reset successful.'); setTimeout(() => navigate('/login'), 1200); } catch (err: any) { setError(err.response?.data?.error || 'Unable to reset password.'); } finally { setLoading(false); } }
  return <AuthShell title="Secure credential reset"><form onSubmit={handleSubmit} className="panel-depth rounded-2xl border border-white/60 bg-paper-raised p-6 sm:p-8"><h2 className="font-display text-xl font-semibold text-ink">Reset password</h2><p className="mt-1 text-sm text-steel">Choose a new password for your account.</p>{error && <p className="mt-5 rounded-lg bg-signal-critical/10 px-3 py-2 font-mono text-xs text-signal-critical">{error}</p>}{message && <p className="mt-5 rounded-lg bg-signal-resolved/10 px-3 py-2 font-mono text-xs text-signal-resolved">{message}</p>}<label htmlFor="reset-email" className="mb-1.5 mt-5 block text-xs font-medium text-steel">Email</label><input id="reset-email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="w-full rounded-lg border border-black/10 bg-white px-3 py-2.5 text-sm transition focus:border-ink/30 focus:outline-none focus:ring-4 focus:ring-ink/8" required /><label htmlFor="new-password" className="mb-1.5 mt-4 block text-xs font-medium text-steel">New password</label><div className="relative"><input id="new-password" type={showPassword ? 'text' : 'password'} value={newPassword} onChange={(event) => setNewPassword(event.target.value)} className="w-full rounded-lg border border-black/10 bg-white px-3 py-2.5 pr-16 text-sm transition focus:border-ink/30 focus:outline-none focus:ring-4 focus:ring-ink/8" required minLength={8} /><button type="button" onClick={() => setShowPassword((current) => !current)} className="absolute right-2 top-1/2 -translate-y-1/2 text-xs text-steel transition hover:text-ink">{showPassword ? 'Hide' : 'Show'}</button></div><button type="submit" disabled={loading} className="mt-5 w-full rounded-lg bg-ink py-2.5 text-sm font-medium text-white shadow-lg shadow-ink/15 transition hover:-translate-y-0.5 hover:bg-ink/90 disabled:opacity-50">{loading ? 'Resetting...' : 'Reset password'}</button><p className="mt-4 text-center text-xs text-steel">Remember your password? <Link to="/login" className="font-medium text-ink hover:underline">Log in</Link></p></form></AuthShell>;
}
